// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB65nlhzsQrhBKLpI2mgbdBhXeAmV3rDIg',
    appId: '1:163941744806:web:8f31ede66ef3d74b553467',
    messagingSenderId: '163941744806',
    projectId: 'projeto-c8086',
    authDomain: 'projeto-c8086.firebaseapp.com',
    storageBucket: 'projeto-c8086.appspot.com',
    measurementId: 'G-E66RWECGCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2mRFbYdhzohzHMKa-PiQo2Ll5y51oebk',
    appId: '1:163941744806:android:4fec77cfb9ce5b03553467',
    messagingSenderId: '163941744806',
    projectId: 'projeto-c8086',
    storageBucket: 'projeto-c8086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Q0TEu48e46LM8NZ1e1HqrD8Fjl9lQqc',
    appId: '1:163941744806:ios:e7aa74fed52f932f553467',
    messagingSenderId: '163941744806',
    projectId: 'projeto-c8086',
    storageBucket: 'projeto-c8086.appspot.com',
    iosBundleId: 'com.example.exportacaoDeArtesanato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Q0TEu48e46LM8NZ1e1HqrD8Fjl9lQqc',
    appId: '1:163941744806:ios:2748642de446541d553467',
    messagingSenderId: '163941744806',
    projectId: 'projeto-c8086',
    storageBucket: 'projeto-c8086.appspot.com',
    iosBundleId: 'com.example.exportacaoDeArtesanato.RunnerTests',
  );
}
